name: Code Style Check

on:
  pull_request:
    branches: ["develop"]

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install poly
        uses: Goldziher/polylint@v0

      - name: Format check
        run: poly fmt --check .

      - name: Lint
        run: poly lint .
